# Generated by Django 2.1.2 on 2018-10-16 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acronym', models.TextField(db_index=True)),
                ('definition', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
